### ISSUE TITLE
hugo mod vendor breaks this site

### ISSUE THREAD

**Issue by davidovich** [bep/algolia-test#1]
I have been trying to learn hugo with it's mod support, and found this repo. 

In a plain checkout this works:

```bash
hugo server
```

But if I do a `hugo mod vendor`, then `hugo server`, 

I get this error:

```
Error: "/Users/david/Documents/dev/hugo/algolia-test/_vendor/github.com/gohugoio/hugo-mod-heroicons" not found: module does not exist
```

In fact, I cannot find the `github.com/gohugoio/hugo-mod-heroicons` under the _vendor dir. Is it because there are no go files at the module root and the go module system removes the files from the vendor folder ?

If I `hugo mod get github.com/gohugoio/hugo-mod-heroicons`: 

```
david$ hugo mod get github.com/gohugoio/hugo-mod-heroicons
go: github.com/gohugoio/hugo-mod-heroicons upgrade => v0.0.0-20200822140006-fc590bc3dc55
```

I then delete the `_vendor` folder

I get: 

```
Error: Error building site: failed to render pages: render of "home" failed: "/Users/david/Documents/dev/hugo/algolia-test/layouts/index.html:11:22": execute of template failed: template: index.html:11:22: executing "main" at <$icon.Content>: nil pointer evaluating resource.Resource.Content
```

hugo version: v0.75.1
go version: go version go1.15 darwin/amd64
MacOS 10.14.6

**Comment by davidovich** [comment]
@bep any pointers ?

**Comment by bep** [comment]
I suggest you take this on the Hugo forum -- I'm a little short on time these days
